### ISSUE TITLE
💡 storage에 업로드된 이미지 삭제 기능

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#133]
### Description
- storage에 업로드된 이미지 삭제 기능: 회원탈퇴, 게시물 수정/삭제

### To-do
- [x] storage에 업로드된 이미지 삭제 함수 추가
- [x] 회원탈퇴(적용)
- [x] 게시물 수정(적용)
- [x] 게시물 삭제(적용)
