### ISSUE TITLE
♻️ 폴더 및 파일 구조 통일

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#142]
### Description
- 폴더 및 파일 구조 통일

### To-do-check
- [x] KimHayeon1
- [x] younainthefish
- [x] suminson97

### To-do
- [x] Components > CommonStyled 폴더 추가
- [x] Styled Component 파일 이름 통일 (ex) StyledHome)
- [x] useHandleFileInp hook 이름 통일 수정
- [x] jsx 문법을 포함하지 않을 경우 tsx -> ts 확장자명 변경
- [x] Styled Component 파일로 분리
