### ISSUE TITLE
:bulb: 회원탈퇴 시, 유저 데이터 삭제

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#149]
### Description
- 회원탈퇴 시, 유저 데이터 삭제

### To-do
- [x] storage에서 프로필 사진 삭제
- [x] storage에서 피드 사진 삭제
- [x] firestore에서 유저 컬렉션 삭제

### ETC
가능하면 추후 서버에서 처리
