### ISSUE TITLE
:recycle: ModalOverlay 스타일 컴포넌트 병합

### ISSUE THREAD

**Issue by suminson97** [yonainthefish/MoMoo#159]
### To-do
- [x] ModalOverlay 스타일 컴포넌트 병합
- [x] 홈피드 간격 수정
- [x] interface 사용 통일
- [x] StyledOverlay 파일 삭제
