### ISSUE TITLE
:books: 앱 출시 준비

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#182]
### Description
- 정보 처리방침 주소 변경 ( /policy -> /privacy)
- 앱 출시를 위한 공식 계정 생성 (id: momoo@gmail.com | password: 123qwe)
- 회원가입 페이지 - 이용약관/데이터 정책 동의 항목 추가
- 회원가입 페이지 - 생년월일 수집(14세 이상 가입 가능) -> 동의 항목
- 사용자가 계정 및 관련 데이터의 삭제를 요청하는 데 사용할 수 있는 링크 필요
  - 스토어 등록정보에 표시되는 앱 또는 개발자 이름 기재
  - 사용자가 계정 삭제를 요청하기 위해 취해야 할 단계를 눈에 띄게 표시
    (개인정보처리방침 혹은 이용약관 페이지에 회원 탈퇴 기능이 있는 화면에 대한 설명 추가)
  - 삭제되거나 보관되는 데이터 유형 및 추가 보관 기간을 지정
- 사용자가 계정을 삭제하지 않고도 데이터의 일부 또는 전체를 삭제하도록 요청는 데 사용할 수 있는 링크 필요
  - 사용자가 데이터 삭제를 요청하기 위해 취해야 할 단계를 눈에 띄게 표시

### To-do
- [x] 주소 변경
- [x] 공식 계정 생성
- [x] 이용약관 동의 항목 추가
- [x] 데이터 정책 동의 추가
- [x] 생년월일 수집 추가 -> 14세 이상 동의
- [x] 개인정보처리방침 수정
  - [x] 개발자 이름 수정
  - [x] 계정 삭제 방법 추가
  - [x] 데이터 보관 기간 지정
  - [x] 사용자 데이터 삭제 방법 추가
