### ISSUE TITLE
:bug: UI 버그

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#183]
### Description
- 게시물 상세페이지 접근 시, 전체 UI가 작게 렌더링 되었다가, 정상 크기로 리플로우/리페인트되는 버그
- 게시물 상세 - 이미지 크기가 작을 시, 의도한 UI보다 작게 렌더링되는 버그 
- 네비 로고 깨짐 1008~1024px
![image](https://github.com/yonainthefish/MoMoo/assets/108985221/460a4069-60ac-400e-8d6c-15d6445ff752)
- Setting - 프로필 수정 -> Setting으로 변경
- Setting - 회원탈퇴 모달 오픈 시, 탑 바는 dimmed되지 않는 버그
- 게시물 모달 - 모바일 - 페이지의 탑 바에 모달 탑 바가 가려지는 버그

### To-do
- [x] 게시물 UI 리플로우/리페인트 버그
- [x] 게시물 UI 사이즈(이미지가 작은 경우)
- [x] 네비 로고 깨짐
- [x] Setting 모바일 - 탑 바 오타
- [x] Setting 모바일 - 탑 바 dimmed
- [x] 게시물 모달 모바일 - 모달 탑 바 가려짐 버그
