### ISSUE TITLE
:bug: 사파리 웹 - 게시물 모달 - 헤더 잘림/스와이프 시 이전 페이지로 이동하지 않는 사용성 이슈 -> 모바일용 페이지 추가

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#215]
### Description
- 헤더 잘림
  - 원인: 모달 오버레이 - position: fixed + top: 0 속성
    아래 이미지를 보면, 시간 위 페이지가 보이지 않는 부분이 top: 0으로 레이아웃 됨
  - 해결: 가장 간단한 방법은 모바일에서 overlay를 렌더링하지 않는다.
- 스와이프 시 이전 페이지로 이동하지 않는 사용성 이슈
  - 여러 번 스와이프 시에도 게시물 업로드만 보인다. (주소상 이전 페이지로 이동되지만, 모달이 계속 띄워져 있어 화면 상 변화 없음)

=> 두 문제를 한 번에 해결할 수 있는 방법: 모바일에서 게시물 업로드/수정 시, 모달이 아닌 페이지로 변경

### To-do
- [x] 업로드/수정 페이지 추가
- [x] 업로드/수정 모달 - 모바일에 관한 코드 삭제
- [x] 라우터 수정
- [x] 업로드/수정 모달을 띄우는 부분 수정 (모바일은 페이지 이동으로)

### ETC
![image](https://github.com/yonainthefish/MoMoo/assets/108985221/f3c7a884-71ba-4567-b0e6-6519d71adf41)
