### ISSUE TITLE
:bug: 뒤로가기 클릭 시, 스플래시로 돌아갈 수 있는 버그

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#224]
### Description
- 상황 1: 뒤로가기 클릭 시, 이전 화면이 스플래시이어도 돌아갈 수 있다.
- 상황 2: 스플래시 화면에서 일정 초가 지나면 login으로 이동된다. (로그인되어 있다면 home으로)
  따라서 뒤로가기를 계속 클릭해도 스플래시, 로그인(혹은 홈) 화면이 무한 반복되는 상황이 발생할 수 있다.
- 원인: path가 '/'이면 스플래시가 렌더링 되기 때문에, 주소를 통해 스플래시 화면에 접근할 수 있다.
- 해결 방법: 스플래시 라우트를 제거하고, 사이트 접속 시 스플래시 화면이 렌더링되도록 변경

### To-do
- [x] 스플래시 라우트 제거
- [x] path '/home'을 모두 '/'로 변경
- [x] 사이트 접속 시 스플래시 화면 렌더링
