### ISSUE TITLE
:bulb: 사용성 개선

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#239]
### Description
- my/setting - 프로필 설정 -> 프로필 변경 / setting -> Edit profile
- 회원가입/프로필 변경 - 프로필 이미지 호버 시, 커서로 변경
- 회원가입/프로필 변경 - image input에 포커스되었을 때, 시각적으로 보이도록 수정
- 회원가입 - 이용약관 읽고 돌아올 때, 체크 유지
- 마이 팝업 닫기 - 배경 클릭 시 / 페이지 이동 시
- 마이 팝업 - open 시, 마이 팝업 내 첫번째 상호작용하는 요소에 포커스
- 게시물 모달 - 필수 항목 안내
- 로그인/회원가입(모바일) - '안녕하세요 모무입니다' 텍스트 제거
- 포인트 컬러 스케일 - 기존보다 선명한 색상으로 변경
- globalStyle - font-size: %로 변경

### To-do
- [x] 프로필 설정 네이밍 변경
- [x] 프로필 이미지 호버 시 커서
- [x] 프로필 이미지 포커스 시각적 처리
- [x] 이용약관 체크 유지
- [x] 마이 팝업
  - 닫기
    - 배경 클릭
  - open 시, 마이 팝업 내 첫번째 상호작용하는 요소에 포커스
- [x] 필수 항목 안내
- [x] 로그인/회원가입 UI 수정
- [x] 글로벌 스타일 수정
