### ISSUE TITLE
:recycle: 홈피드 리팩토링

### ISSUE THREAD

**Issue by suminson97** [yonainthefish/MoMoo#240]
### To-do

- [x]  전체 보기 - 수정 버튼 제거
- [x]  앨범 아랫부분이 잘립니다 (nav제외)
- [x]  앨범 생성 때 이름 입력하고 엔터 누르면 저장
- [ ]  앨범명을 입력하고 저장 버튼을 여러번 누르면, 누른만큼 앨범 생성
- [ ]  정렬 기준 누르고나서 다른 부분 터치했을때 정렬창 닫기
- [ ] 태블릿 h2 위치 조정
- [ ] 태블릿 h2 중단점 조정
- [ ]  앨범 제목 글자수 제한 추가 - 20자
- [ ] edit modal,input modal  간격 조정
