### ISSUE TITLE
:bulb: 앨범 공유 기능

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#253]
### Description
0. nickname - 필수로 변경
1. 앨범 더보기 모달
2. 공유 모달
  - 사용자 닉네임, email 가져오기
    - 방법1: 파이어베이스 getAuth().getUser(uid)
    - 방법2: 모든 사용자 정보를 저장하는 collection 추가
3. 공유된 링크 접속 - 권한 획득 (파이어 스토어 저장)
4. 타인 앨범 상세 렌더링
   타인 피드 상세 렌더링
5. 홈 - 공유 앨범 UI/렌더링
6. 앨범 삭제/이름 변경 -> 공유 앨범 데이터 변경
7. 앨범 공유 대상 제거 -> 공유 앨범 데이터 변경

8. 홈 - 공유 앨범 - 타인 앨범 수정 기능
9. 공유 앨범 - (내) 피드 추가 -> 앨범명이 내 앨범과 같은 경우 -> 식별 가능해야 함

### To-do
- [x] 앨범 더보기 모달 UI
- [x] 공유 모달 UI -> 리디자인
- [x] 타인 앨범/피드 렌더링
- [x] 홈 - 공유 앨범 렌더링
- [x] 홈- 공유 앨범 UI
- 공유 앨범 데이터 변경
  - [x] 홈 - 앨범 삭제 시
  - [x] 공유 모달 - 앨범 공유 대상 제거

### ETC
*Nextjs 레포에서 이어서 작업 [링크](https://github.com/NeedsLap/MOMOO-Nextjs/issues/8)
