### ISSUE TITLE
♻️ Refactor: 게시글 사진 업로드 모바일 UI 수정 

### ISSUE THREAD

**Issue by yonainthefish** [yonainthefish/MoMoo#51]
### Description
- 게시글 업로드 사진 업로드 부분 모바일 대응 필요

### To-do
- [x] 사진 업로드 한장 시 인디케이터 생성되지 않도록 하기
- [x] 모바일 변경 시 사진 업로드 부분 슬라이드 -> 펼쳐지도록 기능 수정
- [x] 사진 선택 최대 3장까지 될 수 있도록
