### ISSUE TITLE
:art: 앨범 상세페이지(피드리스트) UI 구현

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#53]
### Description
- 앨범 상세페이지 UI 구현

### To-do
- [x] 앨범 상세페이지 UI
- [x] 반응형
- [x] 게시글 호버 스타일
- [x] 정렬 - 목록형/앨범형
