### ISSUE TITLE
💡 앨범 상세페이지(피드) 기능

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#56]
### Description
- 앨범 상세페이지(피드) 기능

### To-do
- [x] 앨범형/목록형 UI 전환
- [x] 게시글 리스트 데이터 받아서 뿌려주기
- [x] 새 게시물(현재 앨범에 추가) 모달
- [x] 게시물 수정 모달
