### ISSUE TITLE
:bulb: 게시글 변경 모달 기능 추가

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#82]
### Description
- 게시글 변경 모달 기능 추가

### To-do
- [x] 게시글 삭제 기능 (요나)
  - feed 컬렉션에서 해당 게시글 삭제
  - album 컬렉션에서 해당 게시글이 존재하는 album 문서 수정
- [x] 앨범 변경하기 (요나)
  - 선택/선택취소 한 앨범들 필드의 feedList 배열 수정
- [x] 게시글 수정하기 -> 모달로 (하연)
