### ISSUE TITLE
🎨 게시물 모달 및 게시물 상세 UI 깨짐 수정

### ISSUE THREAD

**Issue by KimHayeon1** [yonainthefish/MoMoo#93]
### Description
- 게시물 모달 및 게시물 상세 UI 깨짐 수정

### To-do
- [x] 게시물 업로드 모달 UI 깨짐 수정
- [x] 게시물 상세 UI 깨짐 수정
- [x] overlay 추가 (재사용)
